name: Publish Docker images and binaries
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  push_to_ghcr:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
      CGO_ENABLED: "0"
      GOFLAGS: "-mod=vendor"
    steps:
      - uses: actions/checkout@v2
      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install bison
      - name: Build mruby
        run: make prepare-mruby
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Set VERSION (if any)
        if: ${{ contains(github.ref, 'refs/tags/v') }}
        id: version
        run: |
          echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/v}
      - name: Prepare files for Docker build
        run: |
          cp /etc/ssl/certs/ca-certificates.crt ./.docker/ca-certificates.crt
      - name: Build binary
        run: |
          env GOOS=linux GOARCH=amd64 go build -ldflags "-s -w -X github.com/anycable/anycable-go/version.version=${{ steps.version.outputs.VERSION }} -X github.com/anycable/anycable-go/version.sha=$(echo "$GITHUB_SHA" | cut -c -7) -X github.com/anycable/anycable-go/version.modifier=pro" -a -o .docker/anycable-go-linux-amd64 cmd/anycable-go/main.go
          .docker/anycable-go-linux-amd64 -v
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Prepare Docker metadata and versions
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/anycable/anycable-go-pro
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha,prefix=
            type=edge,branch=pro-master
      - name: Build and push base images
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .docker/Dockerfile.linux-amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: |
            maintainer=Vladimir Dementyev
            org.opencontainers.image.description=AnyCable WebSocket server (pro version)
            org.opencontainers.image.vendor=Evil Martians
            org.opencontainers.image.url=https://anycable.io
            org.opencontainers.image.source=https://github.com/anycable/anycable-go-pro-releases
            org.opencontainers.image.documentation=https://docs.anycable.io
            org.opencontainers.image.licenses=https://anycable.io/eula
      - name: Prepare Docker metadata and versions for alpine image
        id: meta-alpine
        uses: docker/metadata-action@v3
        with:
          flavor: |
            latest=auto
            prefix=
            suffix=-alpine
          images: |
            ghcr.io/anycable/anycable-go-pro
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=edge,branch=pro-master
      - name: Build and push alpine images
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .docker/Dockerfile.alpine-linux-amd64
          push: true
          tags: ${{ steps.meta-alpine.outputs.tags }}
          labels: |
            maintainer=Vladimir Dementyev
            org.opencontainers.image.description=AnyCable WebSocket server (pro version)
            org.opencontainers.image.vendor=Evil Martians
            org.opencontainers.image.url=https://anycable.io
            org.opencontainers.image.source=https://github.com/anycable/anycable-go-pro-releases
            org.opencontainers.image.documentation=https://docs.anycable.io
            org.opencontainers.image.licenses=https://anycable.io/eula
      - name: Build binary with MRuby
        # Temporary disable buidling MRuby images
        if: ${{ false }}
        env:
          CGO_ENABLED: "1"
        run: |
          env GOOS=linux GOARCH=amd64 go build -tags mrb -ldflags "-s -w -X github.com/anycable/anycable-go/version.version=${{ steps.version.outputs.VERSION }} -X github.com/anycable/anycable-go/version.sha=$(echo "$GITHUB_SHA" | cut -c -7) -X github.com/anycable/anycable-go/version.modifier=pro" -a -o .docker/anycable-go-linux-amd64 cmd/anycable-go/main.go
          .docker/anycable-go-linux-amd64 -v
      - name: Prepare Docker metadata and versions for mrb image
        if: ${{ false }}
        id: meta-mrb
        uses: docker/metadata-action@v3
        with:
          flavor: |
            latest=auto
            prefix=
            suffix=-mrb
          images: |
            ghcr.io/anycable/anycable-go-pro
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=edge,branch=pro-master
      - name: Build and push mrb images
        if: ${{ false }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .docker/Dockerfile.mrb-linux-amd64
          push: true
          tags: ${{ steps.meta-mrb.outputs.tags }}
          labels: |
            maintainer=Vladimir Dementyev
            org.opencontainers.image.description=AnyCable WebSocket server (pro version)
            org.opencontainers.image.vendor=Evil Martians
            org.opencontainers.image.url=https://anycable.io
            org.opencontainers.image.source=https://github.com/anycable/anycable-go-pro-releases
            org.opencontainers.image.documentation=https://docs.anycable.io
            org.opencontainers.image.licenses=https://anycable.io/eula
  upload_binaries:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
      CGO_ENABLED: "0"
      GOFLAGS: "-mod=vendor"
    steps:
      - uses: actions/checkout@v2
      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install bison
      - name: Build mruby
        run: make prepare-mruby
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Set VERSION (if any)
        if: ${{ contains(github.ref, 'refs/tags/v') }}
        id: version
        run: |
          echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/v}
      - name: Build binary
        run: |
          env GOOS=linux GOARCH=amd64 go build -ldflags "-s -w -X github.com/anycable/anycable-go/version.version=${{ steps.version.outputs.VERSION }} -X github.com/anycable/anycable-go/version.sha=$(echo "$GITHUB_SHA" | cut -c -7) -X github.com/anycable/anycable-go/version.modifier=pro" -a -o dist/anycable-go-linux-amd64 cmd/anycable-go/main.go
          dist/anycable-go-linux-amd64 -v
      - name: Build binary with MRuby
        env:
          CGO_ENABLED: "1"
        run: |
          env GOOS=linux GOARCH=amd64 go build -tags mrb -ldflags "-s -w -X github.com/anycable/anycable-go/version.version=${{ steps.version.outputs.VERSION }} -X github.com/anycable/anycable-go/version.sha=$(echo "$GITHUB_SHA" | cut -c -7) -X github.com/anycable/anycable-go/version.modifier=pro" -a -o dist/anycable-go-mrb-linux-amd64 cmd/anycable-go/main.go
          dist/anycable-go-mrb-linux-amd64 -v
      - uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GHCR_TOKEN }}
        with:
          file: "dist/anycable-go-*"
          update_latest_release: true
